// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg0aZ0H36wG45B36WLN9mzsd9wfCcDPX0',
    appId: '1:94668415174:web:e3ae757009ab6a1bb5b7c7',
    messagingSenderId: '94668415174',
    projectId: 'dent-log',
    authDomain: 'dent-log.firebaseapp.com',
    storageBucket: 'dent-log.firebasestorage.app',
    measurementId: 'G-01XSNDYC8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_yb6Dlgb9zzp89tRiCJ7xj-7w9yNHPA',
    appId: '1:94668415174:android:e1fc296fc293a966b5b7c7',
    messagingSenderId: '94668415174',
    projectId: 'dent-log',
    storageBucket: 'dent-log.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_8oo9rY8M0gxJfq1eKxR4JzjasUvb48',
    appId: '1:94668415174:ios:d5d740eb65b2ed36b5b7c7',
    messagingSenderId: '94668415174',
    projectId: 'dent-log',
    storageBucket: 'dent-log.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_8oo9rY8M0gxJfq1eKxR4JzjasUvb48',
    appId: '1:94668415174:ios:d5d740eb65b2ed36b5b7c7',
    messagingSenderId: '94668415174',
    projectId: 'dent-log',
    storageBucket: 'dent-log.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg0aZ0H36wG45B36WLN9mzsd9wfCcDPX0',
    appId: '1:94668415174:web:3f566f2b943d12bbb5b7c7',
    messagingSenderId: '94668415174',
    projectId: 'dent-log',
    authDomain: 'dent-log.firebaseapp.com',
    storageBucket: 'dent-log.firebasestorage.app',
    measurementId: 'G-4FKC4TL3P6',
  );
}
